### ISSUE TITLE
How do I register?

### ISSUE THREAD

**Issue by KaiDevrim** [Yooooomi/your_spotify#39]
I setup the compose file just like what is linked but the ports changed. I can access the app but I do not remember setting a username/password and when I go to register it says that registration is disabled. I cannot click on anything on the menu to the left also.

```docker
your_spotify:
    image: yooooomi/your_spotify_server
    container_name: your_spotify
    restart: always
    ports:
      - "8000:8080"
    links:
      - your_spotify_mongo
    depends_on:
      - your_spotify_mongo
    environment:
      - API_ENDPOINT=http://localhost:8000 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://localhost:4000
      - SPOTIFY_PUBLIC=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
      - CORS=http://localhost:4000,http://localhost:4001
      #- CORS=all
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
  your_spotify_mongo:
    container_name: your_spotify_mongo
    image: mongo
    volumes:
      - ${ROOT}/spotify/db:/data/db
  your_spotify_web:
    image: yooooomi/your_spotify_client
    container_name: your_spotify_web
    restart: always
    ports:
      - "4000:3000"
    environment:
      - API_ENDPOINT=http://localhost:8000
```

**Comment by Yooooomi** [comment]
Hello!

Allowing or disabling is a recent feature I set few weeks ago. Normally, the registrations are allowed by default. Not being able to register could mean that the client cannot access the server because the client tries to know if a user can register. Could you send me a screenshot of the network panel of your web browser when accessing the web application?

Thanks

**Comment by KaiDevrim** [comment]
![Screen Shot 2021-05-21 at 15 57 02](https://user-images.githubusercontent.com/36937771/119205523-4a7ebc80-ba4d-11eb-8bb2-0f7375a83bf4.png)
This is what I see, I do not remember touching any settings for it.

**Comment by Yooooomi** [comment]
Okay I was right. Something in your configuration is preventing the web from requesting the server. Could you send me the console tab as well please so I can see what type of http error you're getting.
My guess is that the server did not start since you changed the name of your mongo container and did not edit the connection url. The mongo endpoint url should look like `MONGO_ENDPOINT=mongodb://your_spotify_mongo:27017/your_spotify`

**Comment by KaiDevrim** [comment]
![image](https://user-images.githubusercontent.com/36937771/119208933-1ad5b180-ba59-11eb-912c-a5ef1134b9c8.png)
i still seem to be getting an error even though I changed the mongo endpoint URL.
```
  your_spotify:
    image: yooooomi/your_spotify_server
    container_name: your_spotify
    restart: always
    ports:
      - "8000:8080"
    links:
      - your_spotify_mongo
    depends_on:
      - your_spotify_mongo
    environment:
      - API_ENDPOINT=http://localhost:8000 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://localhost:4000
      - SPOTIFY_PUBLIC=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
      - CORS=http://localhost:4000,http://localhost:4001
      #- CORS=all
      - MONGO_ENDPOINT=mongodb://your_spotify_mongo:27017/your_spotify
  your_spotify_mongo:
    container_name: your_spotify_mongo
    image: mongo
    volumes:
      - ${ROOT}/spotify/db:/data/db
  your_spotify_web:
    image: yooooomi/your_spotify_client
    container_name: your_spotify_web
    restart: always
    ports:
      - "4000:3000"
    environment:
      - API_ENDPOINT=http://localhost:8000
   ```

**Comment by Yooooomi** [comment]
Ok so it's not a frontend error since it states that it cannot access the server. The server did not started, could you share the logs of the server docker ? Thanks

**Comment by KaiDevrim** [comment]
![image](https://user-images.githubusercontent.com/36937771/119209074-a8190600-ba59-11eb-93f6-65eb371b0637.png)

![image](https://user-images.githubusercontent.com/36937771/119209085-ba933f80-ba59-11eb-9977-22b9d8d136d4.png)

![image](https://user-images.githubusercontent.com/36937771/119209099-c67f0180-ba59-11eb-97d6-106ce0385625.png)

**Comment by Yooooomi** [comment]
Everything seems good. Maybe try recreating the containers but it should work now

**Comment by Yooooomi** [comment]
Oooh I see now, you're accessing the application from 192.xx.xx.xx not from localhost. So when it tries to request localhost there is nothing since the server is on another machine I suppose. If you access the application from 192.xx.xx.xx then the urls in the docker-compose should also be 192.xx.xx.xx and not localhost

**Comment by KaiDevrim** [comment]
I currently have my docker-compose like this:
```
  your_spotify:
    image: yooooomi/your_spotify_server
    container_name: your_spotify
    restart: always
    ports:
      - "8000:8080"
    links:
      - your_spotify_mongo
    depends_on:
      - your_spotify_mongo
    environment:
      - API_ENDPOINT=http://192.168.1.194:8000 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://192.168.1.194:4000
      - SPOTIFY_PUBLIC=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
      # - CORS=http://192.168.1.1:4000,http://localhost:4001
      - CORS=all
      - MONGO_ENDPOINT=mongodb://your_spotify_mongo:27017/your_spotify
  your_spotify_mongo:
    container_name: your_spotify_mongo
    image: mongo
    volumes:
      - ${ROOT}/spotify/db:/data/db
  your_spotify_web:
    image: yooooomi/your_spotify_client
    container_name: your_spotify_web
    restart: always
    ports:
      - "4000:3000"
    environment:
      - API_ENDPOINT=http://192.168.1.194:8000
      ```
it still doesn't work for some reason

**Comment by Yooooomi** [comment]
I have my computer on `192.168.1.75` on my local network, and your docker-compose file with those values changed to mine works:

```yml
version: "3"

services:
  your_spotify:
    image: yooooomi/your_spotify_server
    container_name: your_spotify
    restart: always
    ports:
      - "8000:8080"
    links:
      - your_spotify_mongo
    depends_on:
      - your_spotify_mongo
    environment:
      - API_ENDPOINT=http://192.168.1.75:8000 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://192.168.1.75:4000
      - SPOTIFY_PUBLIC=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
      # - CORS=http://192.168.1.1:4000,http://localhost:4001
      - CORS=all
      - MONGO_ENDPOINT=mongodb://your_spotify_mongo:27017/your_spotify
  your_spotify_mongo:
    container_name: your_spotify_mongo
    image: mongo
    logging:
      driver: none
    volumes:
      - ${ROOT}/spotify/db:/data/db
  your_spotify_web:
    image: yooooomi/your_spotify_client
    container_name: your_spotify_web
    restart: always
    ports:
      - "4000:3000"
    environment:
      - API_ENDPOINT=http://192.168.1.75:8000
```

Try recreating the containers by:
- stopping the docker-compose
- docker-compose rm
- docker-compose up

**Comment by leetosc** [comment]
I have this issue as well.  Running in docker successfully, but registrations are disabled. 

The calls to `/global/preferences` and `/me` are returning an HTML page.  I assume they should be returning a json response?

![image](https://user-images.githubusercontent.com/13279967/119266270-b7aa6300-bbaf-11eb-933d-0c733dbb912d.png)

**Comment by Yooooomi** [comment]
I am running a fresh version of it and tested all the browsers including Safari (Chrome, Firefox, Safari) and I cannot reproduce what is happening to you guys

**Comment by leetosc** [comment]
```yaml
version: "3"

services:
  app:
    container_name: express-mongo
    restart: always
    build: ./server
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://spotify.anacapocloud.ga # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=https://spotify.anacapocloud.ga
      - SPOTIFY_PUBLIC=
      - SPOTIFY_SECRET=
      - CORS=http://localhost:3000,http://localhost:3001,https://spotify.anacapocloud.ga
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
  mongo:
    container_name: mongo
    image: mongo

  web:
    container_name: web
    restart: always
    build: ./client
    ports:
      - "9081:3000"
    environment:
      - API_ENDPOINT=https://spotify.anacapocloud.ga
```

Since the API calls aren't working it can't get `globalPreferences.allowRegistrations`

Request
```
Request URL: https://spotify.anacapocloud.ga/global/preferences
Request Method: GET
Status Code: 200 
Remote Address: [2606:4700:3033::ac43:8249]:443
Referrer Policy: strict-origin-when-cross-origin
```

Response
```
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="Web Application for your spotify"/><link rel="apple-touch-icon" href="/logo192.png"/><link rel="manifest" href="/manifest.json"/><script src="/variables-final.js"></script><title>Your Spotify</title><link href="/static/css/main.bebd27ca.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(e){function t(t){for(var n,l,i=t[0],f=t[1],a=t[2],p=0,s=[];p<i.length;p++)l=i[p],Object.prototype.hasOwnProperty.call(o,l)&&o[l]&&s.push(o[l][0]),o[l]=0;for(n in f)Object.prototype.hasOwnProperty.call(f,n)&&(e[n]=f[n]);for(c&&c(t);s.length;)s.shift()();return u.push.apply(u,a||[]),r()}function r(){for(var e,t=0;t<u.length;t++){for(var r=u[t],n=!0,i=1;i<r.length;i++){var f=r[i];0!==o[f]&&(n=!1)}n&&(u.splice(t--,1),e=l(l.s=r[0]))}return e}var n={},o={1:0},u=[];function l(t){if(n[t])return n[t].exports;var r=n[t]={i:t,l:!1,exports:{}};return e[t].call(r.exports,r,r.exports,l),r.l=!0,r.exports}l.m=e,l.c=n,l.d=function(e,t,r){l.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},l.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},l.t=function(e,t){if(1&t&&(e=l(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(l.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var n in e)l.d(r,n,function(t){return e[t]}.bind(null,n));return r},l.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return l.d(t,"a",t),t},l.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},l.p="/";var i=this.webpackJsonpclient=this.webpackJsonpclient||[],f=i.push.bind(i);i.push=t,i=i.slice();for(var a=0;a<i.length;a++)t(i[a]);var c=f;r()}([])</script><script src="/static/js/2.6f0c1cea.chunk.js"></script><script src="/static/js/main.4ec0daab.chunk.js"></script></body></html>
```

**Comment by Yooooomi** [comment]
Leetosc your requests are currently requesting the frontend and not the server since both urls are the same, that's why you get the please enable JavaScript message. Try setting the API under spotifyapi.domain.com and the client under Spotify.domain.com

**Comment by leetosc** [comment]
Ah that makes sense. I guess I was confused as to what the environment variables meant.  It works now, thanks.

For reference, my working `docker-compose.yml`
```yml
version: "3"

services:
  app:
    container_name: express-mongo
    restart: always
    build: ./server
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://spotifyapi.anacapocloud.ga # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=https://spotify.anacapocloud.ga
      - SPOTIFY_PUBLIC=
      - SPOTIFY_SECRET=
      - CORS=http://localhost:3000,http://localhost:3001,https://spotify.anacapocloud.ga
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
  mongo:
    container_name: mongo
    image: mongo

  web:
    container_name: web
    restart: always
    build: ./client
    ports:
      - "9081:3000"
    environment:
      - API_ENDPOINT=https://spotifyapi.anacapocloud.ga
```

**Comment by Yooooomi** [comment]
@KaiDevrim any news by your side ?

**Comment by KaiDevrim** [comment]
oh i stopped caring about it so i just removed it from my compose file

**Comment by Yooooomi** [comment]
Keeping the guy that tries to help you up to date about the fact that you do not care about it anymore would be the least thing to do :)
Especially if this guy after a few days asks for news to continue to help you

**Comment by Yooooomi** [comment]
@TrezOne sorry to hear that. Can you try putting an S at your API_ENDPOINT in the client service? http -> https

**Comment by TrezOne** [comment]
I'm an idiot. Completely overlooked that. Registration's working now. Thanks @Yooooomi!
